// Movimenti importati una tantum dal file Excel fornito dall'utente
// (Cartel1.xlsx). Ogni "arrotondamento" ricorrente è in realtà un addebito
// dell'assicurazione auto a consumo, quindi va registrato come uscita
// nella categoria Trasporti con nota "Assicurazione Macchina".
export const EXCEL_IMPORT_SEED = [
  { date: '2026-08-27', type: 'income', category: 'Stipendio', amount: 1710.68, note: 'Stipendio' },
  { date: '2026-08-27', type: 'saving', category: 'Altro risparmio', amount: 95, note: 'Importo periodico messo da parte' },
  { date: '2026-08-27', type: 'expense', category: 'Trasporti', amount: 0.4, note: 'Assicurazione Macchina' },
  { date: '2026-08-27', type: 'expense', category: 'Ristoranti e bar', amount: 3.5, note: 'granita e acqua compleanno alessia' },
  { date: '2026-08-27', type: 'expense', category: 'Regali e donazioni', amount: 20, note: 'regalo alessia' },
  { date: '2026-08-28', type: 'expense', category: 'Vinted', amount: 80.99, note: 'BOX VINTED' },
  { date: '2026-08-28', type: 'expense', category: 'Salute e benessere', amount: 14, note: 'barbiere' },
  { date: '2026-08-29', type: 'expense', category: 'Ristoranti e bar', amount: 31, note: 'Panino Aurora' },
  { date: '2026-08-29', type: 'expense', category: 'Trasporti', amount: 70, note: 'Benzina' },
  { date: '2026-08-29', type: 'expense', category: 'Abbonamenti', amount: 21.96, note: 'Abbonamento claude' },
  { date: '2026-08-29', type: 'expense', category: 'Altro', amount: 14.53, note: 'stampante tiktok' },
  { date: '2026-08-29', type: 'expense', category: 'Trasporti', amount: 4.17, note: 'easypark' },
  { date: '2026-08-30', type: 'expense', category: 'Ristoranti e bar', amount: 8, note: 'Montegusto con serena' },
  { date: '2026-08-30', type: 'expense', category: 'Ristoranti e bar', amount: 6, note: 'Yogurtissimo' },
  { date: '2026-08-30', type: 'expense', category: 'Spesa alimentare', amount: 0.34, note: 'Spesa conad' },
  { date: '2026-08-30', type: 'expense', category: 'Trasporti', amount: 1.63, note: 'easypark' },
  { date: '2026-08-31', type: 'expense', category: 'Trasporti', amount: 0.5, note: 'Assicurazione Macchina' },
  { date: '2026-08-31', type: 'expense', category: 'Trasporti', amount: 0.5, note: 'Assicurazione Macchina' },
  { date: '2026-08-31', type: 'expense', category: 'Trasporti', amount: 0.66, note: 'Assicurazione Macchina' },
  { date: '2026-08-31', type: 'expense', category: 'Trasporti', amount: 0.5, note: 'Assicurazione Macchina' },
  { date: '2026-09-01', type: 'expense', category: 'Trasporti', amount: 0.01, note: 'Assicurazione Macchina' },
  { date: '2026-09-01', type: 'expense', category: 'Trasporti', amount: 0.04, note: 'Assicurazione Macchina' },
  { date: '2026-09-01', type: 'expense', category: 'Spesa alimentare', amount: 4.07, note: 'supermercato deco' },
  { date: '2026-09-01', type: 'expense', category: 'Altro', amount: 45.09, note: 'stampante tiktok' },
  { date: '2026-09-02', type: 'expense', category: 'Trasporti', amount: 0.93, note: 'Assicurazione Macchina' },
  { date: '2026-09-03', type: 'expense', category: 'Abbonamenti', amount: 23.98, note: 'Abbonamento netflix' },
  { date: '2026-09-03', type: 'expense', category: 'Svago e tempo libero', amount: 2, note: 'server minecraft' },
  { date: '2026-09-03', type: 'expense', category: 'Ristoranti e bar', amount: 2.5, note: 'bar' },
  { date: '2026-09-03', type: 'expense', category: 'Ristoranti e bar', amount: 3, note: 'montegusto con samuele' },
  { date: '2026-09-03', type: 'expense', category: 'Ristoranti e bar', amount: 1, note: 'Mcdonald con sere' },
  { date: '2026-09-04', type: 'expense', category: 'Shopping e abbigliamento', amount: 60.98, note: 'zalando robe' },
  { date: '2026-09-04', type: 'expense', category: 'Trasporti', amount: 0.5, note: 'Assicurazione Macchina' },
  { date: '2026-09-04', type: 'expense', category: 'Trasporti', amount: 0.91, note: 'Assicurazione Macchina' },
  { date: '2026-09-04', type: 'expense', category: 'Svago e tempo libero', amount: 19, note: 'montegusto serata karaoke' },
  { date: '2026-09-04', type: 'expense', category: 'Vinted', amount: 72.34, note: 'vestiti vinted tiktok' },
  { date: '2026-09-04', type: 'expense', category: 'Vinted', amount: 52.41, note: 'vestiti vinted tiktok' },
  { date: '2026-09-04', type: 'expense', category: 'Vinted', amount: 18.89, note: 'vestiti vinted tiktok' },
  { date: '2026-09-05', type: 'expense', category: 'Ristoranti e bar', amount: 30.9, note: 'sushi con samu' },
  { date: '2026-09-06', type: 'expense', category: 'Ristoranti e bar', amount: 23.9, note: 'trattoria da lorenzo mattinatella' },
  { date: '2026-09-06', type: 'expense', category: 'Ristoranti e bar', amount: 4, note: 'acqua manfredonia e gelato' },
  { date: '2026-09-06', type: 'expense', category: 'Trasporti', amount: 17, note: 'benzina e parcheggio' },
  { date: '2026-09-06', type: 'expense', category: 'Ristoranti e bar', amount: 2, note: 'acqua manfredonia' },
];
